"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "tr" | "en" | "ar"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  tr: {
    daily_work_report: "Günlük Çalışma Raporu",
    machine_selection: "Makine Seçimi",
    basic_info: "Temel Bilgiler",
    personnel: "Personel",
    vehicles: "Araç-Gereç",
    fuel: "Mazot",
    production_summary: "Üretim Özeti",
    pile_details: "Kazık Detayları",
    expenses: "Harcamalar",
    review: "Özet",
    iron_step: "Demir İşçiliği",
    previous: "Önceki",
    next: "Sonraki",
    submit: "Gönder",
    date: "Tarih",
    project: "Proje",
    machine_hours: "Makine Saat",
    total_production: "Toplam İmalat (M)",
    pile_count: "Yapılan Kazık Adedi",
    drilled_pile: "Demir İndirilen Kazık",
    concrete_pile: "Beton Dökülen Kazık",
    engineer: "Müh",
    foreman: "Formen",
    operator: "Operator",
    oiler: "Yağcı",
    welder: "Kaynakçı",
    other: "Diğer",
    total: "Toplam",
    crane: "Vinç",
    loader: "Loader",
    truck: "Kamyon",
    pickup: "Pick Up",
    car: "Binek",
    service: "Servis",
    shift: "Devir",
    incoming_fuel: "Gelen Mazot",
    remaining_fuel: "Kalan",
    daily_fuel_usage: "Günlük Kullanılan Mazot",
    description: "Açıklama",
    amount: "Tutar",
    currency: "IQD",
    notes: "Notlar",
    maintenance_notes: "Bakım / Malzeme / Notlar",
    report_sent_successfully: "Rapor başarıyla gönderildi",
    error_sending_report: "Rapor gönderilirken hata oluştu",
    admin_panel: "Yönetici Paneli",
    email_settings: "E-posta Ayarları",
    user_management: "Kullanıcı Yönetimi",
    custom_fields: "Özel Alanlar",
    email_recipients: "E-posta Alıcıları",
    authorized_users: "Yetkili Kullanıcılar",
    custom_form_fields: "Özel Form Alanları",
    add_email: "E-posta Ekle",
    add_user: "Kullanıcı Ekle",
    add_field: "Alan Ekle",
    edit: "Düzenle",
    add: "Ekle",
    save: "Kaydet",
    cancel: "İptal",
    username: "Kullanıcı Adı",
    field_name: "Alan Adı",
    settings_saved: "Ayarlar kaydedildi",
    error_saving_settings: "Ayarlar kaydedilirken hata oluştu",
    save_settings: "Ayarları Kaydet",
    email: "E-posta",
    user: "Kullanıcı",
    field: "Alan",
    email_preview: "E-posta Önizleme",
    recipients: "Alıcılar",
    close: "Kapat",
    send: "Gönder",
    preview: "Önizleme",
    pile: "Kazık",
    confirm_delete: "Silmek istediğinizden emin misiniz?",
    field_required: "Bu alan zorunludur",
    invalid_email: "Geçersiz e-posta adresi",
  },
  en: {
    daily_work_report: "Daily Work Report",
    machine_selection: "Machine Selection",
    basic_info: "Basic Information",
    personnel: "Personnel",
    vehicles: "Vehicles & Equipment",
    fuel: "Fuel",
    production_summary: "Production Summary",
    pile_details: "Pile Details",
    expenses: "Expenses",
    review: "Review",
    iron_step: "Iron Work",
    previous: "Previous",
    next: "Next",
    submit: "Submit",
    date: "Date",
    project: "Project",
    machine_hours: "Machine Hours",
    total_production: "Total Production (M)",
    pile_count: "Number of Piles Made",
    drilled_pile: "Piles with Steel Lowered",
    concrete_pile: "Piles with Concrete Poured",
    engineer: "Engineer",
    foreman: "Foreman",
    operator: "Operator",
    oiler: "Oiler",
    welder: "Welder",
    other: "Other",
    total: "Total",
    crane: "Crane",
    loader: "Loader",
    truck: "Truck",
    pickup: "Pick Up",
    car: "Car",
    service: "Service",
    shift: "Shift",
    incoming_fuel: "Incoming Fuel",
    remaining_fuel: "Remaining",
    daily_fuel_usage: "Daily Fuel Usage",
    description: "Description",
    amount: "Amount",
    currency: "IQD",
    notes: "Notes",
    maintenance_notes: "Maintenance / Material / Notes",
    report_sent_successfully: "Report sent successfully",
    error_sending_report: "Error sending report",
    admin_panel: "Admin Panel",
    email_settings: "Email Settings",
    user_management: "User Management",
    custom_fields: "Custom Fields",
    email_recipients: "Email Recipients",
    authorized_users: "Authorized Users",
    custom_form_fields: "Custom Form Fields",
    add_email: "Add Email",
    add_user: "Add User",
    add_field: "Add Field",
    edit: "Edit",
    add: "Add",
    save: "Save",
    cancel: "Cancel",
    username: "Username",
    field_name: "Field Name",
    settings_saved: "Settings saved",
    error_saving_settings: "Error saving settings",
    save_settings: "Save Settings",
    email: "Email",
    user: "User",
    field: "Field",
    email_preview: "Email Preview",
    recipients: "Recipients",
    close: "Close",
    send: "Send",
    preview: "Preview",
    pile: "Pile",
    confirm_delete: "Are you sure you want to delete?",
    field_required: "This field is required",
    invalid_email: "Invalid email address",
  },
  ar: {
    daily_work_report: "تقرير العمل اليومي",
    machine_selection: "اختيار الآلة",
    basic_info: "المعلومات الأساسية",
    personnel: "الموظفون",
    vehicles: "المركبات والمعدات",
    fuel: "الوقود",
    production_summary: "ملخص الإنتاج",
    pile_details: "تفاصيل الأكوام",
    expenses: "المصروفات",
    review: "المراجعة",
    iron_step: "أعمال الحديد",
    previous: "السابق",
    next: "التالي",
    submit: "إرسال",
    date: "التاريخ",
    project: "المشروع",
    machine_hours: "ساعات الآلة",
    total_production: "الإنتاج الإجمالي (م)",
    pile_count: "عدد الأكوام المصنوعة",
    drilled_pile: "الأكوام مع الحديد المنخفض",
    concrete_pile: "الأكوام مع الخرسانة المصبوبة",
    engineer: "مهندس",
    foreman: "رئيس عمال",
    operator: "مشغل",
    oiler: "عامل زيوت",
    welder: "لحام",
    other: "أخرى",
    total: "المجموع",
    crane: "رافعة",
    loader: "محمل",
    truck: "شاحنة",
    pickup: "بيك أب",
    car: "سيارة",
    service: "خدمة",
    shift: "وردية",
    incoming_fuel: "الوقود الوارد",
    remaining_fuel: "المتبقي",
    daily_fuel_usage: "استهلاك الوقود اليومي",
    description: "الوصف",
    amount: "المبلغ",
    currency: "دينار عراقي",
    notes: "ملاحظات",
    maintenance_notes: "صيانة / مواد / ملاحظات",
    report_sent_successfully: "تم إرسال التقرير بنجاح",
    error_sending_report: "خطأ في إرسال التقرير",
    admin_panel: "لوحة الإدارة",
    email_settings: "إعدادات البريد الإلكتروني",
    user_management: "إدارة المستخدمين",
    custom_fields: "الحقول المخصصة",
    email_recipients: "مستقبلو البريد الإلكتروني",
    authorized_users: "المستخدمون المخولون",
    custom_form_fields: "حقول النموذج المخصصة",
    add_email: "إضافة بريد إلكتروني",
    add_user: "إضافة مستخدم",
    add_field: "إضافة حقل",
    edit: "تحرير",
    add: "إضافة",
    save: "حفظ",
    cancel: "إلغاء",
    username: "اسم المستخدم",
    field_name: "اسم الحقل",
    settings_saved: "تم حفظ الإعدادات",
    error_saving_settings: "خطأ في حفظ الإعدادات",
    save_settings: "حفظ الإعدادات",
    email: "بريد إلكتروني",
    user: "مستخدم",
    field: "حقل",
    email_preview: "معاينة البريد الإلكتروني",
    recipients: "المستقبلون",
    close: "إغلاق",
    send: "إرسال",
    preview: "معاينة",
    pile: "كومة",
    confirm_delete: "هل أنت متأكد من أنك تريد الحذف؟",
    field_required: "هذا الحقل مطلوب",
    invalid_email: "عنوان بريد إلكتروني غير صالح",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("tr")

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["tr", "en", "ar"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
