"use client"

import { createContext, useContext, useState, useEffect, type ReactNode } from "react"

type Language = "tr" | "en" | "ar"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  tr: {
    daily_work_report: "Günlük Çalışma Raporu",
    machine_selection: "Makine Seçimi",
    basic_info: "Temel Bilgiler",
    info_and_entry: "Bilgi girişi",
    personnel: "Personel",
    personnel_vehicles: "Personel ve Araç-Gereç",
    vehicles: "Araç-Gereç",
    fuel: "Mazot",
    production_summary: "Üretim Özeti",
    pile_details: "Kazık Detayları",
    expenses: "Harcamalar",
    daily_info: "Günlük bilgiler",
    review: "Özet",
    iron_step: "Demir İşçiliği",
    previous: "Önceki",
    next: "Sonraki",
    submit: "Gönder",
    date: "Tarih",
    project: "Proje",
    machine_hours: "Makine Saat",
    total_production: "Kazık İmalatı (m)",
    pile_count: "Kazık Sayısı (Ad.)",
    drilled_pile: "Demir İndirilen Kazık",
    concrete_pile: "Beton Dökülen Kazık",
    engineer: "Müh",
    foreman: "Formen",
    operator: "Operator",
    oiler: "Yağcı",
    welder: "Kaynakçı",
    other: "Diğer",
    total: "Toplam",
    crane: "Vinç",
    loader: "Loader",
    truck: "Kamyon",
    pickup: "Pick Up",
    car: "Binek",
    service: "Servis",
    shift: "Devir",
    incoming_fuel: "Gelen Mazot",
    remaining_fuel: "Kalan",
    daily_fuel_usage: "Mazot Miktarı (lt)",
    description: "Açıklama",
    amount: "Tutar",
    amount_iqd: "Harcama tutarı (IQD)",
    currency: "IQD",
    notes: "Notlar",
    maintenance_notes: "Bakım / Malzeme / Notlar",
    report_sent_successfully: "Rapor başarıyla gönderildi",
    error_sending_report: "Rapor gönderilirken hata oluştu",
    report_submit_error_network:
      "Sunucuya bağlanılamadı (internet zayıf veya kesildi). Wi‑Fi / mobil veriyi kontrol edip tekrar deneyin.",
    report_submit_error_too_large:
      "Gönderi çok büyük olabilir (özellikle fotoğraflar). Birkaç fotoğrafı silin veya daha küçük ekleyip tekrar deneyin.",
    report_submit_error_auth: "Oturum süresi dolmuş olabilir. Çıkış yapıp yeniden giriş yapın.",
    report_submit_error_forbidden: "Bu işlem için yetkiniz yok veya şantiye eşleşmiyor.",
    report_submit_error_server_busy: "Sunucu geçici olarak yanıt veremedi. Bir süre sonra tekrar deneyin.",
    report_submit_error_timeout: "İşlem zaman aşımına uğradı. İnternetinizi kontrol edip tekrar deneyin.",
    report_submit_ref: "Destek için referans",
    admin_panel: "Yönetici Paneli",
    email_settings: "E-posta Ayarları",
    user_management: "Kullanıcı Yönetimi",
    custom_fields: "Özel Alanlar",
    email_recipients: "E-posta Alıcıları",
    authorized_users: "Yetkili Kullanıcılar",
    custom_form_fields: "Özel Form Alanları",
    add_email: "E-posta Ekle",
    add_user: "Kullanıcı Ekle",
    add_field: "Alan Ekle",
    edit: "Düzenle",
    add: "Ekle",
    save: "Kaydet",
    cancel: "İptal",
    username: "Kullanıcı Adı",
    field_name: "Alan Adı",
    settings_saved: "Ayarlar kaydedildi",
    error_saving_settings: "Ayarlar kaydedilirken hata oluştu",
    save_settings: "Ayarları Kaydet",
    email: "E-posta",
    user: "Kullanıcı",
    field: "Alan",
    email_preview: "E-posta Önizleme",
    recipients: "Alıcılar",
    close: "Kapat",
    send: "Gönder",
    preview: "Önizleme",
    pile: "Kazık",
    confirm_delete: "Silmek istediğinizden emin misiniz?",
    field_required: "Bu alan zorunludur",
    invalid_email: "Geçersiz e-posta adresi",
    // Form & dialogs
    add_machine_prompt_title: "Başka makine eklemek istiyor musunuz?",
    add_machine_prompt_message: "Birden fazla makine için ayrı ayrı veri girebilirsiniz. Ek makine eklemek ister misiniz?",
    no_continue: "Hayır, devam et",
    yes_add_machine: "Evet, makine ekle",
    select_machine_or_vehicle: "Makine veya araç seçin",
    machines_section: "Makineler",
    vehicles_section: "Araçlar",
    add_machine_vehicle: "Makine / Araç Ekle",
    fuel_notes_placeholder: "Günlük mazot kullanımı ile ilgili notlar...",
    tip_fuel_step: "Başka şantiyede mazot kullanan makine varsa \"Makine Ekle\" ile ekleyin. Yeni satır için Enter tuşunu da kullanabilirsiniz.",
    expense_type: "Harcama türü",
    expense_cat_santiye: "Şantiye",
    expense_cat_makine: "Makine (Kullanılan kazık makinesi)",
    expense_cat_personel: "Personel",
    expense_cat_yakit: "Yakıt",
    expense_cat_diger: "Diğer",
    expense_description_placeholder: "Harcama açıklaması...",
    tip_expenses: "Yeni satır eklemek için Enter tuşuna basın veya \"Harcama Ekle\" butonunu kullanın.",
    daily_notes: "Önemli Olay/Talep/Not",
    daily_images_label: "Resimler (en fazla 2 adet)",
    remove: "Kaldır",
    add_image_1: "Resim 1 ekle",
    add_image_2: "Resim 2 ekle",
    daily_notes_placeholder: "Gün içi notlarınızı buraya yazabilirsiniz...",
    next_day_planned_work: "Bir sonraki gün için planlanan imalat ve yapılacak işler",
    next_day_planned_work_placeholder: "Her satıra bir madde yazın. Örn: Kazık imalatı devam, Beton dökümü...",
    image_max_size: "Resim en fazla {{max}} MB olabilir.",
    image_upload_error: "Resim yüklenirken hata oluştu.",
    site: "Şantiye",
    all_machines_totals: "Tüm Makinelerin Toplam Değerleri",
    total_machine_hours: "Toplam Makine Saat",
    machine_info_title: "Makine Bilgileri",
    select_machine: "Makine Seçin",
    machine_n: "Makine",
    machine_note: "Makine Notu",
    remaining_piles_last_report: "Kalan kazık (son rapor sonu)",
    total_fuel_used: "Toplam Kullanılan Mazot (Litre)",
    fuel_used_litre: "Kullanılan Mazot (Litre)",
    no_machine_info: "Makine bilgisi bulunamadı. Lütfen makine seçimi yapın.",
    no_machine_selected: "Makine Seçilmedi",
    machine_selection_title: "Makine Seçimi",
    helper_beton_pile: "Bu değer aynı zamanda Beton Dökülen Kazık (Ad.) olarak kullanılır.",
    concrete_pile_count: "Beton Dökülen Kazık (Ad.)",
    total_production_summary_label: "Toplam Kazık İmalatı (m)",
    total_concrete_piles: "Toplam Beton Dökülen Kazık Sayısı (Ad.)",
    add_extra_machine: "Ek Makine Ekle",
    select_extra_machine: "Ek olarak kullanılacak makineyi seçin",
    machine_selection_subtitle: "Çalışma için kullanılacak kazık makinelerini seçin",
    main_machine_selection: "Ana Makine Seçimi",
    selected_machine_label: "Seçilen Makine",
    extra_machines_note: "Ek makineler 2. adım sonrasında eklenebilir.",
    machine_details_title: "Makine Detayları",
    machine: "Makine",
    pile_details_form_title: "Kazık Detayları",
    add_row: "Satır Ekle",
    remaining_piles_count: "Kalan kazık sayısı (Ad.)",
    action: "İşlem",
    tip_pile_details: "Yeni satır eklemek için Enter tuşuna basın veya \"Kazık Ekle\" butonunu kullanın.",
    add_pile: "Kazık Ekle",
    incoming_lt: "Gelen (lt)",
    remaining_lt: "Kalan (lt)",
    used_lt: "Kullanılan (lt)",
    fuel_remaining_site: "Sahada Kalan Mazot (Devir)",
    iron_prepared_today: "Günlük Hazırlanan 12m Demir (Adet)",
    iron_remaining_site: "Sahada Kalan 12m Demir (Adet)",
    sites: "Şantiyeler",
    tip_prefix: "İpucu",
    select_please: "Seçiniz",
    project_summary: "Proje özeti",
    project_summary_caption: "Son rapor sonu itibarıyla. Bugün yapılan, Üretim Özeti adımında girilir; kalan = toplam − bugüne kadar − bugün yapılan.",
    project_status: "Proje durumu",
    status_ongoing: "Devam Eden",
    status_new: "Yeni",
    project_start_date: "İşin başlama tarihi",
    total_piles_in_project: "Projedeki toplam kazık sayısı (Ad.)",
    initial_piles_done_label: "Rapor öncesi yapılan kazık (Ad.)",
    initial_empty_borehole_label: "Rapor öncesi boş foraj (Ad.)",
    done_until_today_excl: "Bugüne kadar yapılan (son rapor sonu, bugün dahil değil)",
    total_diamond_changed: "Toplam Değişen Elmas Sayısı",
    daily_pile_count_label: "O gün yapılan kazık sayısı (Ad.)",
    empty_borehole: "Boş Foraj (Adet)",
    pre_borehole: "Ön Foraj (Adet)",
    total_empty_borehole: "Toplam Boş Foraj (Adet)",
    total_pre_borehole: "Toplam Ön Foraj (Adet)",
    pile_short: "Kazık",
    drilled_short: "Delinen",
    same_as_daily: "O gün yapılan ile aynı",
    done_until_today_incl: "Bugüne kadar yapılan (bugün dahil)",
    done_until_today_excl_short: "Bugüne kadar yapılan (bugün dahil değil)",
    concrete_poured_short: "Beton Dökülen",
    pile_details_warning: "Yapılan kazık sayısı {count} olarak girildi; kazık detaylarında sadece {entered} adet giriş var. Lütfen en az {count} kazık için delinen/not bilgisi girin.",
    iron_on_site: "Sahada Bulunan 12m Demir (Adet)",
    iron_lowered: "İndirilen 12m Demir (Adet)",
    home: "Anasayfa",
    data_entry: "Bilgi girişi",
    operator_entry: "Makine girişi",
  },
  en: {
    daily_work_report: "Daily Work Report",
    machine_selection: "Machine Selection",
    basic_info: "Basic Information",
    info_and_entry: "Info & entry",
    personnel: "Personnel",
    personnel_vehicles: "Personnel & Vehicles",
    vehicles: "Vehicles & Equipment",
    fuel: "Fuel",
    production_summary: "Production Summary",
    pile_details: "Pile Details",
    expenses: "Expenses",
    daily_info: "Daily info",
    review: "Review",
    iron_step: "Iron Work",
    previous: "Previous",
    next: "Next",
    submit: "Submit",
    date: "Date",
    project: "Project",
    machine_hours: "Machine Hours",
    total_production: "Pile Production (m)",
    pile_count: "Pile Count (pcs)",
    drilled_pile: "Piles with Steel Lowered",
    concrete_pile: "Piles with Concrete Poured",
    engineer: "Engineer",
    foreman: "Foreman",
    operator: "Operator",
    oiler: "Oiler",
    welder: "Welder",
    other: "Other",
    total: "Total",
    crane: "Crane",
    loader: "Loader",
    truck: "Truck",
    pickup: "Pick Up",
    car: "Car",
    service: "Service",
    shift: "Shift",
    incoming_fuel: "Incoming Fuel",
    remaining_fuel: "Remaining",
    daily_fuel_usage: "Fuel (lt)",
    description: "Description",
    amount: "Amount",
    amount_iqd: "Amount (IQD)",
    currency: "IQD",
    notes: "Notes",
    maintenance_notes: "Maintenance / Material / Notes",
    report_sent_successfully: "Report sent successfully",
    error_sending_report: "Error sending report",
    report_submit_error_network:
      "Could not reach the server (weak or dropped connection). Check Wi‑Fi / mobile data and try again.",
    report_submit_error_too_large:
      "The submission may be too large (often photos). Remove a few photos or use smaller images, then try again.",
    report_submit_error_auth: "Your session may have expired. Sign out and sign in again.",
    report_submit_error_forbidden: "You are not allowed to do this, or the site does not match your assignment.",
    report_submit_error_server_busy: "The server is temporarily unavailable. Please try again in a moment.",
    report_submit_error_timeout: "The request timed out. Check your connection and try again.",
    report_submit_ref: "Reference for support",
    admin_panel: "Admin Panel",
    email_settings: "Email Settings",
    user_management: "User Management",
    custom_fields: "Custom Fields",
    email_recipients: "Email Recipients",
    authorized_users: "Authorized Users",
    custom_form_fields: "Custom Form Fields",
    add_email: "Add Email",
    add_user: "Add User",
    add_field: "Add Field",
    edit: "Edit",
    add: "Add",
    save: "Save",
    cancel: "Cancel",
    username: "Username",
    field_name: "Field Name",
    settings_saved: "Settings saved",
    error_saving_settings: "Error saving settings",
    save_settings: "Save Settings",
    email: "Email",
    user: "User",
    field: "Field",
    email_preview: "Email Preview",
    recipients: "Recipients",
    close: "Close",
    send: "Send",
    preview: "Preview",
    pile: "Pile",
    confirm_delete: "Are you sure you want to delete?",
    field_required: "This field is required",
    invalid_email: "Invalid email address",
    add_machine_prompt_title: "Do you want to add another machine?",
    add_machine_prompt_message: "You can enter data separately for multiple machines. Would you like to add an extra machine?",
    no_continue: "No, continue",
    yes_add_machine: "Yes, add machine",
    select_machine_or_vehicle: "Select machine or vehicle",
    machines_section: "Machines",
    vehicles_section: "Vehicles",
    add_machine_vehicle: "Add Machine / Vehicle",
    fuel_notes_placeholder: "Notes about daily fuel usage...",
    tip_fuel_step: "If a machine uses fuel at another site, add it with \"Add Machine\". You can also use Enter for a new row.",
    expense_type: "Expense type",
    expense_cat_santiye: "Site",
    expense_cat_makine: "Machine (Piling machine used)",
    expense_cat_personel: "Personnel",
    expense_cat_yakit: "Fuel",
    expense_cat_diger: "Other",
    expense_description_placeholder: "Expense description...",
    tip_expenses: "Press Enter to add a new row or use the \"Add Expense\" button.",
    daily_notes: "Daily notes",
    daily_images_label: "Images (max 2)",
    remove: "Remove",
    add_image_1: "Add image 1",
    add_image_2: "Add image 2",
    daily_notes_placeholder: "Write your daily notes here...",
    next_day_planned_work: "Planned manufacturing and work for the next day",
    next_day_planned_work_placeholder: "Briefly describe planned work for tomorrow...",
    image_max_size: "Image must be at most {{max}} MB.",
    image_upload_error: "Error uploading image.",
    site: "Site",
    all_machines_totals: "Total Values for All Machines",
    total_machine_hours: "Total Machine Hours",
    machine_info_title: "Machine Information",
    select_machine: "Select Machine",
    machine_n: "Machine",
    machine_note: "Machine Note",
    remaining_piles_last_report: "Remaining piles (last report)",
    total_fuel_used: "Total Fuel Used (Litre)",
    fuel_used_litre: "Fuel Used (Litre)",
    no_machine_info: "No machine information found. Please select a machine.",
    no_machine_selected: "No Machine Selected",
    machine_selection_title: "Machine Selection",
    helper_beton_pile: "This value is also used as Poured Concrete Piles (pcs).",
    concrete_pile_count: "Poured Concrete Piles (pcs)",
    total_production_summary_label: "Total Pile Production (m)",
    total_concrete_piles: "Total Poured Concrete Piles (pcs)",
    add_extra_machine: "Add Extra Machine",
    select_extra_machine: "Select the machine to be used additionally",
    machine_selection_subtitle: "Select the piling machines to be used for work",
    main_machine_selection: "Main Machine Selection",
    selected_machine_label: "Selected Machine",
    extra_machines_note: "Extra machines can be added after step 2.",
    machine_details_title: "Machine Details",
    machine: "Machine",
    pile_details_form_title: "Pile Details",
    add_row: "Add Row",
    remaining_piles_count: "Remaining pile count (pcs)",
    action: "Action",
    tip_pile_details: "Press Enter to add a new row or use the \"Add Pile\" button.",
    add_pile: "Add Pile",
    incoming_lt: "Incoming (lt)",
    remaining_lt: "Remaining (lt)",
    used_lt: "Used (lt)",
    fuel_remaining_site: "Fuel Remaining on Site (Shift)",
    iron_prepared_today: "12m Iron Prepared Today (pcs)",
    iron_remaining_site: "12m Iron Remaining on Site (pcs)",
    sites: "Sites",
    tip_prefix: "Tip",
    select_please: "Select",
    project_summary: "Project summary",
    project_summary_caption: "As of last report. Today's work is entered in Production Summary; remaining = total − done until yesterday − today.",
    project_status: "Project status",
    status_ongoing: "Ongoing",
    status_new: "New",
    project_start_date: "Project start date",
    total_piles_in_project: "Total piles in project (pcs)",
    initial_piles_done_label: "Piles done before reports (pcs)",
    initial_empty_borehole_label: "Empty borehole before reports (pcs)",
    done_until_today_excl: "Done until today (excluding today)",
    total_diamond_changed: "Total Diamond Count Changed",
    daily_pile_count_label: "Piles done today (pcs)",
    empty_borehole: "Empty Borehole (pcs)",
    pre_borehole: "Pre Borehole (pcs)",
    total_empty_borehole: "Total Empty Borehole (pcs)",
    total_pre_borehole: "Total Pre Borehole (pcs)",
    pile_short: "Pile",
    drilled_short: "Drilled",
    same_as_daily: "Same as daily",
    done_until_today_incl: "Done until today (incl. today)",
    done_until_today_excl_short: "Done until today (excl. today)",
    concrete_poured_short: "Concrete Poured",
    pile_details_warning: "Pile count entered as {count}; only {entered} detail entries. Please enter drilled/notes for at least {count} piles.",
    iron_on_site: "12m Iron on Site (pcs)",
    iron_lowered: "12m Iron Lowered (pcs)",
    home: "Home",
    data_entry: "Data entry",
    operator_entry: "Machine entry",
  },
  ar: {
    daily_work_report: "تقرير العمل اليومي",
    machine_selection: "اختيار الآلة",
    basic_info: "المعلومات الأساسية",
    info_and_entry: "إدخال المعلومات",
    personnel: "الموظفون",
    personnel_vehicles: "الموظفون والمركبات",
    vehicles: "المركبات والمعدات",
    fuel: "الوقود",
    production_summary: "ملخص الإنتاج",
    pile_details: "تفاصيل الأكوام",
    expenses: "المصروفات",
    daily_info: "المعلومات اليومية",
    review: "المراجعة",
    iron_step: "أعمال الحديد",
    previous: "السابق",
    next: "التالي",
    submit: "إرسال",
    date: "التاريخ",
    project: "المشروع",
    machine_hours: "ساعات الآلة",
    total_production: "الإنتاج الإجمالي (م)",
    pile_count: "عدد الأكوام المصنوعة",
    drilled_pile: "الأكوام مع الحديد المنخفض",
    concrete_pile: "الأكوام مع الخرسانة المصبوبة",
    engineer: "مهندس",
    foreman: "رئيس عمال",
    operator: "مشغل",
    oiler: "عامل زيوت",
    welder: "لحام",
    other: "أخرى",
    total: "المجموع",
    crane: "رافعة",
    loader: "محمل",
    truck: "شاحنة",
    pickup: "بيك أب",
    car: "سيارة",
    service: "خدمة",
    shift: "وردية",
    incoming_fuel: "الوقود الوارد",
    remaining_fuel: "المتبقي",
    daily_fuel_usage: "كمية الوقود (لتر)",
    description: "الوصف",
    amount: "المبلغ",
    amount_iqd: "المبلغ (دينار عراقي)",
    currency: "دينار عراقي",
    notes: "ملاحظات",
    maintenance_notes: "صيانة / مواد / ملاحظات",
    report_sent_successfully: "تم إرسال التقرير بنجاح",
    error_sending_report: "خطأ في إرسال التقرير",
    report_submit_error_network:
      "تعذر الاتصال بالخادم (إنترنت ضعيف أو انقطع). تحقق من الواي فاي أو بيانات الجوال وحاول مرة أخرى.",
    report_submit_error_too_large:
      "قد يكون الإرسال كبيراً جداً (غالباً الصور). احذف بعض الصور أو استخدم صوراً أصغر ثم أعد المحاولة.",
    report_submit_error_auth: "قد تكون الجلسة منتهية. سجّل الخروج ثم الدخول من جديد.",
    report_submit_error_forbidden: "ليس لديك صلاحية أو الموقع لا يطابق تعيينك.",
    report_submit_error_server_busy: "الخادم غير متاح مؤقتاً. حاول بعد قليل.",
    report_submit_error_timeout: "انتهت مهلة الطلب. تحقق من الاتصال وحاول مرة أخرى.",
    report_submit_ref: "مرجع للدعم",
    admin_panel: "لوحة الإدارة",
    email_settings: "إعدادات البريد الإلكتروني",
    user_management: "إدارة المستخدمين",
    custom_fields: "الحقول المخصصة",
    email_recipients: "مستقبلو البريد الإلكتروني",
    authorized_users: "المستخدمون المخولون",
    custom_form_fields: "حقول النموذج المخصصة",
    add_email: "إضافة بريد إلكتروني",
    add_user: "إضافة مستخدم",
    add_field: "إضافة حقل",
    edit: "تحرير",
    add: "إضافة",
    save: "حفظ",
    cancel: "إلغاء",
    username: "اسم المستخدم",
    field_name: "اسم الحقل",
    settings_saved: "تم حفظ الإعدادات",
    error_saving_settings: "خطأ في حفظ الإعدادات",
    save_settings: "حفظ الإعدادات",
    email: "بريد إلكتروني",
    user: "مستخدم",
    field: "حقل",
    email_preview: "معاينة البريد الإلكتروني",
    recipients: "المستقبلون",
    close: "إغلاق",
    send: "إرسال",
    preview: "معاينة",
    pile: "كومة",
    confirm_delete: "هل أنت متأكد من أنك تريد الحذف؟",
    field_required: "هذا الحقل مطلوب",
    invalid_email: "عنوان بريد إلكتروني غير صالح",
    add_machine_prompt_title: "هل تريد إضافة آلة أخرى؟",
    add_machine_prompt_message: "يمكنك إدخال البيانات بشكل منفصل لآلات متعددة. هل ترغب في إضافة آلة إضافية؟",
    no_continue: "لا، متابعة",
    yes_add_machine: "نعم، إضافة آلة",
    select_machine_or_vehicle: "اختر الآلة أو المركبة",
    machines_section: "الآلات",
    vehicles_section: "المركبات",
    add_machine_vehicle: "إضافة آلة / مركبة",
    fuel_notes_placeholder: "ملاحظات حول استهلاك الوقود اليومي...",
    tip_fuel_step: "إذا كانت الآلة تستخدم الوقود في موقع آخر، أضفها بـ \"إضافة آلة\". يمكنك أيضاً استخدام Enter لصف جديد.",
    expense_type: "نوع المصروف",
    expense_cat_santiye: "الموقع",
    expense_cat_makine: "الآلة (آلة الركائز المستخدمة)",
    expense_cat_personel: "الموظفون",
    expense_cat_yakit: "الوقود",
    expense_cat_diger: "أخرى",
    expense_description_placeholder: "وصف المصروف...",
    tip_expenses: "اضغط Enter لإضافة صف جديد أو استخدم زر \"إضافة مصروف\".",
    daily_notes: "الملاحظات اليومية",
    daily_images_label: "الصور (حد أقصى 2)",
    remove: "إزالة",
    add_image_1: "إضافة صورة 1",
    add_image_2: "إضافة صورة 2",
    daily_notes_placeholder: "اكتب ملاحظاتك اليومية هنا...",
    next_day_planned_work: "الإنتاج والأعمال المخططة لليوم التالي",
    next_day_planned_work_placeholder: "اذكر بإيجاز الأعمال المخططة لغداً...",
    image_max_size: "يجب ألا تتجاوز الصورة {{max}} ميجابايت.",
    image_upload_error: "خطأ في تحميل الصورة.",
    site: "الموقع",
    all_machines_totals: "إجمالي قيم جميع الآلات",
    total_machine_hours: "إجمالي ساعات الآلة",
    machine_info_title: "معلومات الآلة",
    select_machine: "اختر الآلة",
    machine_n: "آلة",
    machine_note: "ملاحظة الآلة",
    remaining_piles_last_report: "الأكوام المتبقية (آخر تقرير)",
    total_fuel_used: "إجمالي الوقود المستخدم (لتر)",
    fuel_used_litre: "الوقود المستخدم (لتر)",
    no_machine_info: "لم يتم العثور على معلومات الآلة. يرجى اختيار آلة.",
    no_machine_selected: "لم يتم اختيار آلة",
    machine_selection_title: "اختيار الآلة",
    helper_beton_pile: "تستخدم هذه القيمة أيضاً كأكوام الخرسانة المصبوبة (عدد).",
    concrete_pile_count: "أكوام الخرسانة المصبوبة (عدد)",
    total_production_summary_label: "إجمالي إنتاج الأكوام (م)",
    total_concrete_piles: "إجمالي أكوام الخرسانة المصبوبة (عدد)",
    add_extra_machine: "إضافة آلة إضافية",
    select_extra_machine: "اختر الآلة الإضافية",
    machine_selection_subtitle: "اختر آلات الركائز المستخدمة في العمل",
    main_machine_selection: "اختيار الآلة الرئيسية",
    selected_machine_label: "الآلة المختارة",
    extra_machines_note: "يمكن إضافة آلات إضافية بعد الخطوة 2.",
    machine_details_title: "تفاصيل الآلة",
    machine: "آلة",
    pile_details_form_title: "تفاصيل الأكوام",
    add_row: "إضافة صف",
    remaining_piles_count: "عدد الأكوام المتبقية (عدد)",
    action: "إجراء",
    tip_pile_details: "اضغط Enter لإضافة صف جديد أو استخدم زر \"إضافة كومة\".",
    add_pile: "إضافة كومة",
    incoming_lt: "الوارد (لتر)",
    remaining_lt: "المتبقي (لتر)",
    used_lt: "المستخدم (لتر)",
    fuel_remaining_site: "الوقود المتبقي في الموقع (وردية)",
    iron_prepared_today: "حديد 12م المُجهّز اليوم (عدد)",
    iron_remaining_site: "حديد 12م المتبقي في الموقع (عدد)",
    sites: "المواقع",
    tip_prefix: "نصيحة",
    select_please: "اختر",
    project_summary: "ملخص المشروع",
    project_summary_caption: "اعتباراً من آخر تقرير. يُدخل عمل اليوم في ملخص الإنتاج؛ المتبقي = الإجمالي − المنفذ حتى أمس − اليوم.",
    project_status: "حالة المشروع",
    status_ongoing: "قيد التنفيذ",
    status_new: "جديد",
    project_start_date: "تاريخ بدء المشروع",
    total_piles_in_project: "إجمالي الأكوام في المشروع (عدد)",
    initial_piles_done_label: "الأكوام المنفذة قبل التقارير (عدد)",
    initial_empty_borehole_label: "الحفر الفارغ قبل التقارير (عدد)",
    done_until_today_excl: "المُنفذ حتى اليوم (بدون اليوم)",
    total_diamond_changed: "إجمالي عدد الماس المتغير",
    daily_pile_count_label: "الأكوام المنفذة اليوم (عدد)",
    empty_borehole: "الحفر الفارغ (عدد)",
    pre_borehole: "الحفر المسبق (عدد)",
    total_empty_borehole: "إجمالي الحفر الفارغ (عدد)",
    total_pre_borehole: "إجمالي الحفر المسبق (عدد)",
    pile_short: "كومة",
    drilled_short: "مثقوب",
    same_as_daily: "نفس اليوم",
    done_until_today_incl: "المُنفذ حتى اليوم (بما فيه اليوم)",
    done_until_today_excl_short: "المُنفذ حتى اليوم (بدون اليوم)",
    concrete_poured_short: "الخرسانة المصبوبة",
    pile_details_warning: "تم إدخال عدد الأكوام {count}؛ فقط {entered} تفاصيل. يرجى إدخال مثقوب/ملاحظات لـ {count} أكوام على الأقل.",
    iron_on_site: "حديد 12م في الموقع (عدد)",
    iron_lowered: "حديد 12م منخفض (عدد)",
    home: "الرئيسية",
    data_entry: "إدخال البيانات",
    operator_entry: "إدخال الآلة",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("tr")

  // Load language from localStorage on mount
  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language
    if (savedLanguage && ["tr", "en", "ar"].includes(savedLanguage)) {
      setLanguage(savedLanguage)
    }
  }, [])

  // Save language to localStorage when it changes
  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem("language", lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
